hooks_enabled = true

[model]
temperature = 0
name = "nvidia/nemotron-3-super-120b-a12b"

[[hooks]]
name='test_before_tool'
trigger='before_tool'
command='python3 ./scripts/test_tool.py'

[[hooks]]
name='test_before_agent'
trigger='before_agent'
command='python3 ./scripts/test_tool.py'

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "."]